// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chapters.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createChapter = `-- name: CreateChapter :exec
INSERT INTO chapters (id, project_id, volume_id, title, content, plain_text, word_count, sort_order, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateChapterParams struct {
	ID        string
	ProjectID string
	VolumeID  sql.NullString
	Title     string
	Content   string
	PlainText sql.NullString
	WordCount sql.NullInt64
	SortOrder int64
	Status    sql.NullString
}

func (q *Queries) CreateChapter(ctx context.Context, arg CreateChapterParams) error {
	_, err := q.db.ExecContext(ctx, createChapter,
		arg.ID,
		arg.ProjectID,
		arg.VolumeID,
		arg.Title,
		arg.Content,
		arg.PlainText,
		arg.WordCount,
		arg.SortOrder,
		arg.Status,
	)
	return err
}

const deleteChapterByID = `-- name: DeleteChapterByID :execrows
DELETE FROM chapters
WHERE id = ?
`

func (q *Queries) DeleteChapterByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChapterByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getChapterByID = `-- name: GetChapterByID :one
SELECT
    id,
    project_id,
    COALESCE(volume_id, '') AS volume_id,
    title,
    COALESCE(content, '') AS content,
    COALESCE(plain_text, '') AS plain_text,
    COALESCE(word_count, 0) AS word_count,
    COALESCE(sort_order, 0) AS sort_order,
    COALESCE(status, 'draft') AS status,
    COALESCE(created_at, '') AS created_at,
    COALESCE(updated_at, '') AS updated_at
FROM chapters
WHERE id = ?
`

type GetChapterByIDRow struct {
	ID        string
	ProjectID string
	VolumeID  string
	Title     string
	Content   string
	PlainText string
	WordCount int64
	SortOrder int64
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetChapterByID(ctx context.Context, id string) (GetChapterByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getChapterByID, id)
	var i GetChapterByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.VolumeID,
		&i.Title,
		&i.Content,
		&i.PlainText,
		&i.WordCount,
		&i.SortOrder,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChaptersByProject = `-- name: ListChaptersByProject :many
SELECT
    id,
    project_id,
    COALESCE(volume_id, '') AS volume_id,
    title,
    COALESCE(content, '') AS content,
    COALESCE(plain_text, '') AS plain_text,
    COALESCE(word_count, 0) AS word_count,
    COALESCE(sort_order, 0) AS sort_order,
    COALESCE(status, 'draft') AS status,
    COALESCE(created_at, '') AS created_at,
    COALESCE(updated_at, '') AS updated_at
FROM chapters
WHERE project_id = ?
ORDER BY CASE WHEN volume_id IS NULL THEN 0 ELSE 1 END ASC, volume_id ASC, sort_order ASC, created_at ASC
`

type ListChaptersByProjectRow struct {
	ID        string
	ProjectID string
	VolumeID  string
	Title     string
	Content   string
	PlainText string
	WordCount int64
	SortOrder int64
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListChaptersByProject(ctx context.Context, projectID string) ([]ListChaptersByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listChaptersByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChaptersByProjectRow
	for rows.Next() {
		var i ListChaptersByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.VolumeID,
			&i.Title,
			&i.Content,
			&i.PlainText,
			&i.WordCount,
			&i.SortOrder,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootChapterIDsByScope = `-- name: ListRootChapterIDsByScope :many
SELECT id
FROM chapters
WHERE project_id = ? AND volume_id IS NULL AND id <> ?
ORDER BY sort_order ASC, created_at ASC
`

type ListRootChapterIDsByScopeParams struct {
	ProjectID string
	ID        string
}

func (q *Queries) ListRootChapterIDsByScope(ctx context.Context, arg ListRootChapterIDsByScopeParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRootChapterIDsByScope, arg.ProjectID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumeChapterIDsByScope = `-- name: ListVolumeChapterIDsByScope :many
SELECT id
FROM chapters
WHERE project_id = ? AND volume_id = ? AND id <> ?
ORDER BY sort_order ASC, created_at ASC
`

type ListVolumeChapterIDsByScopeParams struct {
	ProjectID string
	VolumeID  sql.NullString
	ID        string
}

func (q *Queries) ListVolumeChapterIDsByScope(ctx context.Context, arg ListVolumeChapterIDsByScopeParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listVolumeChapterIDsByScope, arg.ProjectID, arg.VolumeID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRootChapterSortOrder = `-- name: NextRootChapterSortOrder :one
SELECT COALESCE(MAX(sort_order), -1) + 1
FROM chapters
WHERE project_id = ? AND volume_id IS NULL
`

func (q *Queries) NextRootChapterSortOrder(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextRootChapterSortOrder, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const nextVolumeChapterSortOrder = `-- name: NextVolumeChapterSortOrder :one
SELECT COALESCE(MAX(sort_order), -1) + 1
FROM chapters
WHERE project_id = ? AND volume_id = ?
`

type NextVolumeChapterSortOrderParams struct {
	ProjectID string
	VolumeID  sql.NullString
}

func (q *Queries) NextVolumeChapterSortOrder(ctx context.Context, arg NextVolumeChapterSortOrderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextVolumeChapterSortOrder, arg.ProjectID, arg.VolumeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const refreshProjectWordCount = `-- name: RefreshProjectWordCount :exec
UPDATE projects
SET word_count = COALESCE((SELECT SUM(word_count) FROM chapters WHERE project_id = ?), 0),
    updated_at = CURRENT_TIMESTAMP
WHERE projects.id = ?
`

type RefreshProjectWordCountParams struct {
	ProjectID string
	ID        string
}

func (q *Queries) RefreshProjectWordCount(ctx context.Context, arg RefreshProjectWordCountParams) error {
	_, err := q.db.ExecContext(ctx, refreshProjectWordCount, arg.ProjectID, arg.ID)
	return err
}

const reorderChapterByID = `-- name: ReorderChapterByID :exec
UPDATE chapters
SET sort_order = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type ReorderChapterByIDParams struct {
	SortOrder int64
	ID        string
}

func (q *Queries) ReorderChapterByID(ctx context.Context, arg ReorderChapterByIDParams) error {
	_, err := q.db.ExecContext(ctx, reorderChapterByID, arg.SortOrder, arg.ID)
	return err
}

const reorderChapterByProject = `-- name: ReorderChapterByProject :exec
UPDATE chapters
SET sort_order = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND project_id = ?
`

type ReorderChapterByProjectParams struct {
	SortOrder int64
	ID        string
	ProjectID string
}

func (q *Queries) ReorderChapterByProject(ctx context.Context, arg ReorderChapterByProjectParams) error {
	_, err := q.db.ExecContext(ctx, reorderChapterByProject, arg.SortOrder, arg.ID, arg.ProjectID)
	return err
}

const updateChapterByID = `-- name: UpdateChapterByID :execrows
UPDATE chapters
SET volume_id = ?,
    title = ?,
    content = ?,
    plain_text = ?,
    word_count = ?,
    sort_order = ?,
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateChapterByIDParams struct {
	VolumeID  sql.NullString
	Title     string
	Content   string
	PlainText sql.NullString
	WordCount sql.NullInt64
	SortOrder int64
	Status    sql.NullString
	ID        string
}

func (q *Queries) UpdateChapterByID(ctx context.Context, arg UpdateChapterByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateChapterByID,
		arg.VolumeID,
		arg.Title,
		arg.Content,
		arg.PlainText,
		arg.WordCount,
		arg.SortOrder,
		arg.Status,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateChapterVolumeByID = `-- name: UpdateChapterVolumeByID :exec
UPDATE chapters
SET volume_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateChapterVolumeByIDParams struct {
	VolumeID sql.NullString
	ID       string
}

func (q *Queries) UpdateChapterVolumeByID(ctx context.Context, arg UpdateChapterVolumeByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateChapterVolumeByID, arg.VolumeID, arg.ID)
	return err
}

const volumeExistsInProject = `-- name: VolumeExistsInProject :one
SELECT EXISTS(
    SELECT 1 FROM volumes WHERE id = ? AND project_id = ? LIMIT 1
)
`

type VolumeExistsInProjectParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) VolumeExistsInProject(ctx context.Context, arg VolumeExistsInProjectParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, volumeExistsInProject, arg.ID, arg.ProjectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
