// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package sqlc

import (
	"context"
	"database/sql"
)

const characterExistsInProject = `-- name: CharacterExistsInProject :one
SELECT EXISTS(
    SELECT 1 FROM characters WHERE id = ? AND project_id = ? LIMIT 1
)
`

type CharacterExistsInProjectParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) CharacterExistsInProject(ctx context.Context, arg CharacterExistsInProjectParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, characterExistsInProject, arg.ID, arg.ProjectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCharacter = `-- name: CreateCharacter :exec
INSERT INTO characters (
    id,
    project_id,
    name,
    alias_json,
    summary,
    traits_json,
    background,
    avatar_url,
    personality_prompt,
    speech_pattern,
    current_state,
    custom_status_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCharacterParams struct {
	ID                string
	ProjectID         string
	Name              string
	AliasJson         string
	Summary           sql.NullString
	TraitsJson        string
	Background        sql.NullString
	AvatarUrl         sql.NullString
	PersonalityPrompt sql.NullString
	SpeechPattern     sql.NullString
	CurrentState      sql.NullString
	CustomStatusJson  string
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) error {
	_, err := q.db.ExecContext(ctx, createCharacter,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.AliasJson,
		arg.Summary,
		arg.TraitsJson,
		arg.Background,
		arg.AvatarUrl,
		arg.PersonalityPrompt,
		arg.SpeechPattern,
		arg.CurrentState,
		arg.CustomStatusJson,
	)
	return err
}

const createCharacterRelation = `-- name: CreateCharacterRelation :exec
INSERT INTO character_relations (
    id,
    project_id,
    from_id,
    to_id,
    type,
    strength,
    notes,
    valid_from_chapter_id,
    valid_until_chapter_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCharacterRelationParams struct {
	ID                  string
	ProjectID           string
	FromID              string
	ToID                string
	Type                string
	Strength            int64
	Notes               sql.NullString
	ValidFromChapterID  sql.NullString
	ValidUntilChapterID sql.NullString
}

func (q *Queries) CreateCharacterRelation(ctx context.Context, arg CreateCharacterRelationParams) error {
	_, err := q.db.ExecContext(ctx, createCharacterRelation,
		arg.ID,
		arg.ProjectID,
		arg.FromID,
		arg.ToID,
		arg.Type,
		arg.Strength,
		arg.Notes,
		arg.ValidFromChapterID,
		arg.ValidUntilChapterID,
	)
	return err
}

const deleteCharacterByID = `-- name: DeleteCharacterByID :execrows
DELETE FROM characters
WHERE id = ?
`

func (q *Queries) DeleteCharacterByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCharacterByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCharacterRelationByID = `-- name: DeleteCharacterRelationByID :execrows
DELETE FROM character_relations
WHERE id = ?
`

func (q *Queries) DeleteCharacterRelationByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCharacterRelationByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCharacterByID = `-- name: GetCharacterByID :one
SELECT
    id,
    project_id,
    name,
    alias_json,
    COALESCE(summary, '') AS summary,
    traits_json,
    COALESCE(background, '') AS background,
    COALESCE(avatar_url, '') AS avatar_url,
    COALESCE(personality_prompt, '') AS personality_prompt,
    COALESCE(speech_pattern, '') AS speech_pattern,
    COALESCE(current_state, '') AS current_state,
    custom_status_json,
    created_at,
    updated_at
FROM characters
WHERE id = ?
`

type GetCharacterByIDRow struct {
	ID                string
	ProjectID         string
	Name              string
	AliasJson         string
	Summary           string
	TraitsJson        string
	Background        string
	AvatarUrl         string
	PersonalityPrompt string
	SpeechPattern     string
	CurrentState      string
	CustomStatusJson  string
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

func (q *Queries) GetCharacterByID(ctx context.Context, id string) (GetCharacterByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCharacterByID, id)
	var i GetCharacterByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.AliasJson,
		&i.Summary,
		&i.TraitsJson,
		&i.Background,
		&i.AvatarUrl,
		&i.PersonalityPrompt,
		&i.SpeechPattern,
		&i.CurrentState,
		&i.CustomStatusJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCharacterRelationByID = `-- name: GetCharacterRelationByID :one
SELECT
    id,
    project_id,
    from_id,
    to_id,
    type,
    COALESCE(strength, 50) AS strength,
    COALESCE(notes, '') AS notes,
    COALESCE(valid_from_chapter_id, '') AS valid_from_chapter_id,
    COALESCE(valid_until_chapter_id, '') AS valid_until_chapter_id,
    created_at,
    updated_at
FROM character_relations
WHERE id = ?
`

type GetCharacterRelationByIDRow struct {
	ID                  string
	ProjectID           string
	FromID              string
	ToID                string
	Type                string
	Strength            int64
	Notes               string
	ValidFromChapterID  string
	ValidUntilChapterID string
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}

func (q *Queries) GetCharacterRelationByID(ctx context.Context, id string) (GetCharacterRelationByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCharacterRelationByID, id)
	var i GetCharacterRelationByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FromID,
		&i.ToID,
		&i.Type,
		&i.Strength,
		&i.Notes,
		&i.ValidFromChapterID,
		&i.ValidUntilChapterID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCharacterRelationsByCharacter = `-- name: ListCharacterRelationsByCharacter :many
SELECT
    id,
    project_id,
    from_id,
    to_id,
    type,
    COALESCE(strength, 50) AS strength,
    COALESCE(notes, '') AS notes,
    COALESCE(valid_from_chapter_id, '') AS valid_from_chapter_id,
    COALESCE(valid_until_chapter_id, '') AS valid_until_chapter_id,
    created_at,
    updated_at
FROM character_relations
WHERE project_id = ? AND (from_id = ? OR to_id = ?)
ORDER BY updated_at DESC, created_at DESC
`

type ListCharacterRelationsByCharacterParams struct {
	ProjectID string
	FromID    string
	ToID      string
}

type ListCharacterRelationsByCharacterRow struct {
	ID                  string
	ProjectID           string
	FromID              string
	ToID                string
	Type                string
	Strength            int64
	Notes               string
	ValidFromChapterID  string
	ValidUntilChapterID string
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}

func (q *Queries) ListCharacterRelationsByCharacter(ctx context.Context, arg ListCharacterRelationsByCharacterParams) ([]ListCharacterRelationsByCharacterRow, error) {
	rows, err := q.db.QueryContext(ctx, listCharacterRelationsByCharacter, arg.ProjectID, arg.FromID, arg.ToID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharacterRelationsByCharacterRow
	for rows.Next() {
		var i ListCharacterRelationsByCharacterRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FromID,
			&i.ToID,
			&i.Type,
			&i.Strength,
			&i.Notes,
			&i.ValidFromChapterID,
			&i.ValidUntilChapterID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharacterRelationsByProject = `-- name: ListCharacterRelationsByProject :many
SELECT
    id,
    project_id,
    from_id,
    to_id,
    type,
    COALESCE(strength, 50) AS strength,
    COALESCE(notes, '') AS notes,
    COALESCE(valid_from_chapter_id, '') AS valid_from_chapter_id,
    COALESCE(valid_until_chapter_id, '') AS valid_until_chapter_id,
    created_at,
    updated_at
FROM character_relations
WHERE project_id = ?
ORDER BY updated_at DESC, created_at DESC
`

type ListCharacterRelationsByProjectRow struct {
	ID                  string
	ProjectID           string
	FromID              string
	ToID                string
	Type                string
	Strength            int64
	Notes               string
	ValidFromChapterID  string
	ValidUntilChapterID string
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}

func (q *Queries) ListCharacterRelationsByProject(ctx context.Context, projectID string) ([]ListCharacterRelationsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listCharacterRelationsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharacterRelationsByProjectRow
	for rows.Next() {
		var i ListCharacterRelationsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FromID,
			&i.ToID,
			&i.Type,
			&i.Strength,
			&i.Notes,
			&i.ValidFromChapterID,
			&i.ValidUntilChapterID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharactersByProject = `-- name: ListCharactersByProject :many
SELECT
    id,
    project_id,
    name,
    alias_json,
    COALESCE(summary, '') AS summary,
    traits_json,
    COALESCE(background, '') AS background,
    COALESCE(avatar_url, '') AS avatar_url,
    COALESCE(personality_prompt, '') AS personality_prompt,
    COALESCE(speech_pattern, '') AS speech_pattern,
    COALESCE(current_state, '') AS current_state,
    custom_status_json,
    created_at,
    updated_at
FROM characters
WHERE project_id = ?
ORDER BY updated_at DESC, created_at DESC
`

type ListCharactersByProjectRow struct {
	ID                string
	ProjectID         string
	Name              string
	AliasJson         string
	Summary           string
	TraitsJson        string
	Background        string
	AvatarUrl         string
	PersonalityPrompt string
	SpeechPattern     string
	CurrentState      string
	CustomStatusJson  string
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

func (q *Queries) ListCharactersByProject(ctx context.Context, projectID string) ([]ListCharactersByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listCharactersByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharactersByProjectRow
	for rows.Next() {
		var i ListCharactersByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.AliasJson,
			&i.Summary,
			&i.TraitsJson,
			&i.Background,
			&i.AvatarUrl,
			&i.PersonalityPrompt,
			&i.SpeechPattern,
			&i.CurrentState,
			&i.CustomStatusJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCharacterByID = `-- name: UpdateCharacterByID :execrows
UPDATE characters
SET name = ?,
    alias_json = ?,
    summary = ?,
    traits_json = ?,
    background = ?,
    avatar_url = ?,
    personality_prompt = ?,
    speech_pattern = ?,
    current_state = ?,
    custom_status_json = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateCharacterByIDParams struct {
	Name              string
	AliasJson         string
	Summary           sql.NullString
	TraitsJson        string
	Background        sql.NullString
	AvatarUrl         sql.NullString
	PersonalityPrompt sql.NullString
	SpeechPattern     sql.NullString
	CurrentState      sql.NullString
	CustomStatusJson  string
	ID                string
}

func (q *Queries) UpdateCharacterByID(ctx context.Context, arg UpdateCharacterByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCharacterByID,
		arg.Name,
		arg.AliasJson,
		arg.Summary,
		arg.TraitsJson,
		arg.Background,
		arg.AvatarUrl,
		arg.PersonalityPrompt,
		arg.SpeechPattern,
		arg.CurrentState,
		arg.CustomStatusJson,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
