// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: creative_workflows.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getCreativeWorkflowByProject = `-- name: GetCreativeWorkflowByProject :one
SELECT
    project_id,
    COALESCE(template_id, '') AS template_id,
    COALESCE(pitch_line, '') AS pitch_line,
    target_audience_json,
    core_promises_json,
    COALESCE(pace_contract, '') AS pace_contract,
    golden_chapters_json,
    created_at,
    updated_at
FROM creative_workflows
WHERE project_id = ?
`

type GetCreativeWorkflowByProjectRow struct {
	ProjectID          string
	TemplateID         string
	PitchLine          string
	TargetAudienceJson string
	CorePromisesJson   string
	PaceContract       string
	GoldenChaptersJson string
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
}

func (q *Queries) GetCreativeWorkflowByProject(ctx context.Context, projectID string) (GetCreativeWorkflowByProjectRow, error) {
	row := q.db.QueryRowContext(ctx, getCreativeWorkflowByProject, projectID)
	var i GetCreativeWorkflowByProjectRow
	err := row.Scan(
		&i.ProjectID,
		&i.TemplateID,
		&i.PitchLine,
		&i.TargetAudienceJson,
		&i.CorePromisesJson,
		&i.PaceContract,
		&i.GoldenChaptersJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCreativeWorkflow = `-- name: UpsertCreativeWorkflow :exec
INSERT INTO creative_workflows (
    project_id,
    template_id,
    pitch_line,
    target_audience_json,
    core_promises_json,
    pace_contract,
    golden_chapters_json
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(project_id) DO UPDATE SET
    template_id = excluded.template_id,
    pitch_line = excluded.pitch_line,
    target_audience_json = excluded.target_audience_json,
    core_promises_json = excluded.core_promises_json,
    pace_contract = excluded.pace_contract,
    golden_chapters_json = excluded.golden_chapters_json,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertCreativeWorkflowParams struct {
	ProjectID          string
	TemplateID         sql.NullString
	PitchLine          string
	TargetAudienceJson string
	CorePromisesJson   string
	PaceContract       string
	GoldenChaptersJson string
}

func (q *Queries) UpsertCreativeWorkflow(ctx context.Context, arg UpsertCreativeWorkflowParams) error {
	_, err := q.db.ExecContext(ctx, upsertCreativeWorkflow,
		arg.ProjectID,
		arg.TemplateID,
		arg.PitchLine,
		arg.TargetAudienceJson,
		arg.CorePromisesJson,
		arg.PaceContract,
		arg.GoldenChaptersJson,
	)
	return err
}
