// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: inspiration_notes.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createInspirationNote = `-- name: CreateInspirationNote :exec
INSERT INTO inspiration_notes (
    id,
    project_id,
    chapter_id,
    chapter_title,
    title,
    content
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateInspirationNoteParams struct {
	ID           string
	ProjectID    string
	ChapterID    sql.NullString
	ChapterTitle string
	Title        string
	Content      string
}

func (q *Queries) CreateInspirationNote(ctx context.Context, arg CreateInspirationNoteParams) error {
	_, err := q.db.ExecContext(ctx, createInspirationNote,
		arg.ID,
		arg.ProjectID,
		arg.ChapterID,
		arg.ChapterTitle,
		arg.Title,
		arg.Content,
	)
	return err
}

const deleteInspirationNoteByID = `-- name: DeleteInspirationNoteByID :execrows
DELETE FROM inspiration_notes
WHERE id = ?
`

func (q *Queries) DeleteInspirationNoteByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInspirationNoteByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listInspirationNotesByProject = `-- name: ListInspirationNotesByProject :many
SELECT
    id,
    project_id,
    COALESCE(chapter_id, '') AS chapter_id,
    COALESCE(chapter_title, '') AS chapter_title,
    title,
    content,
    created_at,
    updated_at
FROM inspiration_notes
WHERE project_id = ?
ORDER BY created_at DESC, updated_at DESC
`

type ListInspirationNotesByProjectRow struct {
	ID           string
	ProjectID    string
	ChapterID    string
	ChapterTitle string
	Title        string
	Content      string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

func (q *Queries) ListInspirationNotesByProject(ctx context.Context, projectID string) ([]ListInspirationNotesByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listInspirationNotesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInspirationNotesByProjectRow
	for rows.Next() {
		var i ListInspirationNotesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ChapterID,
			&i.ChapterTitle,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
