// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createLocation = `-- name: CreateLocation :exec
INSERT INTO locations (
    id,
    project_id,
    name,
    description,
    climate,
    culture,
    geography,
    atmosphere,
    parent_id,
    image_url
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateLocationParams struct {
	ID          string
	ProjectID   string
	Name        string
	Description sql.NullString
	Climate     sql.NullString
	Culture     sql.NullString
	Geography   sql.NullString
	Atmosphere  sql.NullString
	ParentID    sql.NullString
	ImageUrl    sql.NullString
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) error {
	_, err := q.db.ExecContext(ctx, createLocation,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.Climate,
		arg.Culture,
		arg.Geography,
		arg.Atmosphere,
		arg.ParentID,
		arg.ImageUrl,
	)
	return err
}

const createLocationRelation = `-- name: CreateLocationRelation :exec
INSERT INTO location_relations (
    id,
    project_id,
    from_id,
    to_id,
    type,
    distance,
    notes
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateLocationRelationParams struct {
	ID        string
	ProjectID string
	FromID    string
	ToID      string
	Type      string
	Distance  sql.NullString
	Notes     sql.NullString
}

func (q *Queries) CreateLocationRelation(ctx context.Context, arg CreateLocationRelationParams) error {
	_, err := q.db.ExecContext(ctx, createLocationRelation,
		arg.ID,
		arg.ProjectID,
		arg.FromID,
		arg.ToID,
		arg.Type,
		arg.Distance,
		arg.Notes,
	)
	return err
}

const deleteLocationByID = `-- name: DeleteLocationByID :execrows
DELETE FROM locations
WHERE id = ?
`

func (q *Queries) DeleteLocationByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLocationByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLocationRelationByID = `-- name: DeleteLocationRelationByID :execrows
DELETE FROM location_relations
WHERE id = ?
`

func (q *Queries) DeleteLocationRelationByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLocationRelationByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT
    id,
    project_id,
    name,
    COALESCE(description, '') AS description,
    COALESCE(climate, '') AS climate,
    COALESCE(culture, '') AS culture,
    COALESCE(geography, '') AS geography,
    COALESCE(atmosphere, '') AS atmosphere,
    COALESCE(parent_id, '') AS parent_id,
    COALESCE(image_url, '') AS image_url,
    COALESCE(created_at, '') AS created_at,
    COALESCE(updated_at, '') AS updated_at
FROM locations
WHERE id = ?
`

type GetLocationByIDRow struct {
	ID          string
	ProjectID   string
	Name        string
	Description string
	Climate     string
	Culture     string
	Geography   string
	Atmosphere  string
	ParentID    string
	ImageUrl    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetLocationByID(ctx context.Context, id string) (GetLocationByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLocationByID, id)
	var i GetLocationByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Climate,
		&i.Culture,
		&i.Geography,
		&i.Atmosphere,
		&i.ParentID,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocationRelationByID = `-- name: GetLocationRelationByID :one
SELECT
    id,
    project_id,
    from_id,
    to_id,
    type,
    COALESCE(distance, '') AS distance,
    COALESCE(notes, '') AS notes,
    COALESCE(created_at, '') AS created_at,
    COALESCE(updated_at, '') AS updated_at
FROM location_relations
WHERE id = ?
`

type GetLocationRelationByIDRow struct {
	ID        string
	ProjectID string
	FromID    string
	ToID      string
	Type      string
	Distance  string
	Notes     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetLocationRelationByID(ctx context.Context, id string) (GetLocationRelationByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLocationRelationByID, id)
	var i GetLocationRelationByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FromID,
		&i.ToID,
		&i.Type,
		&i.Distance,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocationRelationsByLocation = `-- name: ListLocationRelationsByLocation :many
SELECT
    id,
    project_id,
    from_id,
    to_id,
    type,
    COALESCE(distance, '') AS distance,
    COALESCE(notes, '') AS notes,
    COALESCE(created_at, '') AS created_at,
    COALESCE(updated_at, '') AS updated_at
FROM location_relations
WHERE project_id = ? AND (from_id = ? OR to_id = ?)
ORDER BY updated_at DESC, created_at DESC
`

type ListLocationRelationsByLocationParams struct {
	ProjectID string
	FromID    string
	ToID      string
}

type ListLocationRelationsByLocationRow struct {
	ID        string
	ProjectID string
	FromID    string
	ToID      string
	Type      string
	Distance  string
	Notes     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListLocationRelationsByLocation(ctx context.Context, arg ListLocationRelationsByLocationParams) ([]ListLocationRelationsByLocationRow, error) {
	rows, err := q.db.QueryContext(ctx, listLocationRelationsByLocation, arg.ProjectID, arg.FromID, arg.ToID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationRelationsByLocationRow
	for rows.Next() {
		var i ListLocationRelationsByLocationRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FromID,
			&i.ToID,
			&i.Type,
			&i.Distance,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationRelationsByProject = `-- name: ListLocationRelationsByProject :many
SELECT
    id,
    project_id,
    from_id,
    to_id,
    type,
    COALESCE(distance, '') AS distance,
    COALESCE(notes, '') AS notes,
    COALESCE(created_at, '') AS created_at,
    COALESCE(updated_at, '') AS updated_at
FROM location_relations
WHERE project_id = ?
ORDER BY updated_at DESC, created_at DESC
`

type ListLocationRelationsByProjectRow struct {
	ID        string
	ProjectID string
	FromID    string
	ToID      string
	Type      string
	Distance  string
	Notes     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListLocationRelationsByProject(ctx context.Context, projectID string) ([]ListLocationRelationsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listLocationRelationsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationRelationsByProjectRow
	for rows.Next() {
		var i ListLocationRelationsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FromID,
			&i.ToID,
			&i.Type,
			&i.Distance,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationsByProject = `-- name: ListLocationsByProject :many
SELECT
    id,
    project_id,
    name,
    COALESCE(description, '') AS description,
    COALESCE(climate, '') AS climate,
    COALESCE(culture, '') AS culture,
    COALESCE(geography, '') AS geography,
    COALESCE(atmosphere, '') AS atmosphere,
    COALESCE(parent_id, '') AS parent_id,
    COALESCE(image_url, '') AS image_url,
    COALESCE(created_at, '') AS created_at,
    COALESCE(updated_at, '') AS updated_at
FROM locations
WHERE project_id = ?
ORDER BY CASE WHEN parent_id IS NULL THEN 0 ELSE 1 END ASC, parent_id ASC, updated_at DESC, created_at DESC
`

type ListLocationsByProjectRow struct {
	ID          string
	ProjectID   string
	Name        string
	Description string
	Climate     string
	Culture     string
	Geography   string
	Atmosphere  string
	ParentID    string
	ImageUrl    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListLocationsByProject(ctx context.Context, projectID string) ([]ListLocationsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listLocationsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationsByProjectRow
	for rows.Next() {
		var i ListLocationsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.Climate,
			&i.Culture,
			&i.Geography,
			&i.Atmosphere,
			&i.ParentID,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationExistsInProject = `-- name: LocationExistsInProject :one
SELECT EXISTS(
    SELECT 1 FROM locations WHERE id = ? AND project_id = ? LIMIT 1
)
`

type LocationExistsInProjectParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) LocationExistsInProject(ctx context.Context, arg LocationExistsInProjectParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, locationExistsInProject, arg.ID, arg.ProjectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateLocationByID = `-- name: UpdateLocationByID :execrows
UPDATE locations
SET name = ?,
    description = ?,
    climate = ?,
    culture = ?,
    geography = ?,
    atmosphere = ?,
    parent_id = ?,
    image_url = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateLocationByIDParams struct {
	Name        string
	Description sql.NullString
	Climate     sql.NullString
	Culture     sql.NullString
	Geography   sql.NullString
	Atmosphere  sql.NullString
	ParentID    sql.NullString
	ImageUrl    sql.NullString
	ID          string
}

func (q *Queries) UpdateLocationByID(ctx context.Context, arg UpdateLocationByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLocationByID,
		arg.Name,
		arg.Description,
		arg.Climate,
		arg.Culture,
		arg.Geography,
		arg.Atmosphere,
		arg.ParentID,
		arg.ImageUrl,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
