// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Chapter struct {
	ID        string
	ProjectID string
	VolumeID  sql.NullString
	Title     string
	Content   string
	PlainText sql.NullString
	WordCount sql.NullInt64
	SortOrder int64
	Status    sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Character struct {
	ID                string
	ProjectID         string
	Name              string
	AliasJson         string
	Summary           sql.NullString
	TraitsJson        string
	Background        sql.NullString
	AvatarUrl         sql.NullString
	PersonalityPrompt sql.NullString
	SpeechPattern     sql.NullString
	CurrentState      sql.NullString
	CustomStatusJson  string
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type CharacterRelation struct {
	ID                  string
	ProjectID           string
	FromID              string
	ToID                string
	Type                string
	Strength            int64
	Notes               sql.NullString
	ValidFromChapterID  sql.NullString
	ValidUntilChapterID sql.NullString
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}

type CreativeWorkflow struct {
	ProjectID          string
	TemplateID         sql.NullString
	PitchLine          string
	TargetAudienceJson string
	CorePromisesJson   string
	PaceContract       string
	GoldenChaptersJson string
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
}

type InspirationNote struct {
	ID           string
	ProjectID    string
	ChapterID    sql.NullString
	ChapterTitle string
	Title        string
	Content      string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Location struct {
	ID          string
	ProjectID   string
	Name        string
	Description sql.NullString
	Climate     sql.NullString
	Culture     sql.NullString
	Geography   sql.NullString
	Atmosphere  sql.NullString
	ParentID    sql.NullString
	ImageUrl    sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type LocationRelation struct {
	ID        string
	ProjectID string
	FromID    string
	ToID      string
	Type      string
	Distance  sql.NullString
	Notes     sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Project struct {
	ID          string
	Title       string
	Description sql.NullString
	CoverPath   sql.NullString
	WordCount   sql.NullInt64
	Status      sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Setting struct {
	Key   string
	Value string
}

type Snapshot struct {
	ID        string
	ProjectID string
	ChapterID sql.NullString
	Label     sql.NullString
	Content   string
	WordCount sql.NullInt64
	Trigger   sql.NullString
	CreatedAt sql.NullTime
}

type StoryHarnessBatch struct {
	BatchID            string
	ProjectID          string
	ChapterID          string
	ChapterTitle       string
	CommittedAt        int64
	Source             string
	ChangeRequestsJson string
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
}

type StoryHarnessChangeRequest struct {
	ID                  string
	BatchID             string
	ProjectID           string
	ChapterID           string
	Category            string
	Priority            string
	Status              string
	Title               string
	Description         string
	SuggestedChangeJson string
	EvidenceJson        string
	Source              string
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}

type Timeline struct {
	ID            string
	ProjectID     string
	Name          string
	Description   string
	StartTimeJson string
	EndTimeJson   string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type TimelineEvent struct {
	ID               string
	ProjectID        string
	TimelineID       string
	Title            string
	Description      string
	StoryTimeJson    string
	Duration         string
	Impact           string
	ParticipantsJson string
	LocationIdsJson  string
	ChapterIdsJson   string
	EventType        string
	Importance       int64
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type Volume struct {
	ID        string
	ProjectID string
	Title     string
	SortOrder int64
	CreatedAt sql.NullTime
}
