// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Chapter struct {
	ID        string
	ProjectID string
	VolumeID  sql.NullString
	Title     string
	Content   string
	PlainText sql.NullString
	WordCount sql.NullInt64
	SortOrder int64
	Status    sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Character struct {
	ID                string
	ProjectID         string
	Name              string
	AliasJson         string
	Summary           sql.NullString
	TraitsJson        string
	Background        sql.NullString
	AvatarUrl         sql.NullString
	PersonalityPrompt sql.NullString
	SpeechPattern     sql.NullString
	CurrentState      sql.NullString
	CustomStatusJson  string
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type CharacterRelation struct {
	ID                  string
	ProjectID           string
	FromID              string
	ToID                string
	Type                string
	Strength            int64
	Notes               sql.NullString
	ValidFromChapterID  sql.NullString
	ValidUntilChapterID sql.NullString
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}

type Location struct {
	ID          string
	ProjectID   string
	Name        string
	Description sql.NullString
	Climate     sql.NullString
	Culture     sql.NullString
	Geography   sql.NullString
	Atmosphere  sql.NullString
	ParentID    sql.NullString
	ImageUrl    sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type LocationRelation struct {
	ID        string
	ProjectID string
	FromID    string
	ToID      string
	Type      string
	Distance  sql.NullString
	Notes     sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Project struct {
	ID          string
	Title       string
	Description sql.NullString
	CoverPath   sql.NullString
	WordCount   sql.NullInt64
	Status      sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Setting struct {
	Key   string
	Value string
}

type Snapshot struct {
	ID        string
	ProjectID string
	ChapterID sql.NullString
	Label     sql.NullString
	Content   string
	WordCount sql.NullInt64
	Trigger   sql.NullString
	CreatedAt sql.NullTime
}

type Volume struct {
	ID        string
	ProjectID string
	Title     string
	SortOrder int64
	CreatedAt sql.NullTime
}
