// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, title, description, cover_path, status)
VALUES (?, ?, ?, ?, ?)
`

type CreateProjectParams struct {
	ID          string
	Title       string
	Description sql.NullString
	CoverPath   sql.NullString
	Status      sql.NullString
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.CoverPath,
		arg.Status,
	)
	return err
}

const deleteProjectByID = `-- name: DeleteProjectByID :execrows
DELETE FROM projects
WHERE id = ?
`

func (q *Queries) DeleteProjectByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProjectByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProject = `-- name: GetProject :one
SELECT
    p.id,
    p.title,
    COALESCE(p.description, '') AS description,
    COALESCE(p.cover_path, '') AS cover_path,
    COALESCE(p.word_count, 0) AS word_count,
    COALESCE(p.status, 'draft') AS status,
    CAST((
        SELECT COUNT(1)
        FROM chapters c
        WHERE c.project_id = p.id
    ) AS INTEGER) AS chapter_count,
    p.created_at,
    p.updated_at
FROM projects p
WHERE p.id = ?
`

type GetProjectRow struct {
	ID           string
	Title        string
	Description  string
	CoverPath    string
	WordCount    int64
	Status       string
	ChapterCount int64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

func (q *Queries) GetProject(ctx context.Context, id string) (GetProjectRow, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CoverPath,
		&i.WordCount,
		&i.Status,
		&i.ChapterCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT
    p.id,
    p.title,
    COALESCE(p.description, '') AS description,
    COALESCE(p.cover_path, '') AS cover_path,
    COALESCE(p.word_count, 0) AS word_count,
    COALESCE(p.status, 'draft') AS status,
    CAST((
        SELECT COUNT(1)
        FROM chapters c
        WHERE c.project_id = p.id
    ) AS INTEGER) AS chapter_count,
    p.created_at,
    p.updated_at
FROM projects p
ORDER BY p.updated_at DESC, p.created_at DESC
`

type ListProjectsRow struct {
	ID           string
	Title        string
	Description  string
	CoverPath    string
	WordCount    int64
	Status       string
	ChapterCount int64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CoverPath,
			&i.WordCount,
			&i.Status,
			&i.ChapterCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectExists = `-- name: ProjectExists :one
SELECT EXISTS(
    SELECT 1 FROM projects WHERE id = ? LIMIT 1
)
`

func (q *Queries) ProjectExists(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, projectExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateProjectByID = `-- name: UpdateProjectByID :execrows
UPDATE projects
SET title = ?,
    description = ?,
    cover_path = ?,
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateProjectByIDParams struct {
	Title       string
	Description sql.NullString
	CoverPath   sql.NullString
	Status      sql.NullString
	ID          string
}

func (q *Queries) UpdateProjectByID(ctx context.Context, arg UpdateProjectByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProjectByID,
		arg.Title,
		arg.Description,
		arg.CoverPath,
		arg.Status,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
