// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: story_harness.sql

package sqlc

import (
	"context"
)

const countStoryHarnessChangeRequestsByChapterAndStatus = `-- name: CountStoryHarnessChangeRequestsByChapterAndStatus :one
SELECT COUNT(1)
FROM story_harness_change_requests
WHERE chapter_id = ? AND status = ?
`

type CountStoryHarnessChangeRequestsByChapterAndStatusParams struct {
	ChapterID string
	Status    string
}

func (q *Queries) CountStoryHarnessChangeRequestsByChapterAndStatus(ctx context.Context, arg CountStoryHarnessChangeRequestsByChapterAndStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStoryHarnessChangeRequestsByChapterAndStatus, arg.ChapterID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStoryHarnessBatch = `-- name: CreateStoryHarnessBatch :exec
INSERT INTO story_harness_batches (
    batch_id,
    project_id,
    chapter_id,
    chapter_title,
    committed_at,
    source,
    change_requests_json
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateStoryHarnessBatchParams struct {
	BatchID            string
	ProjectID          string
	ChapterID          string
	ChapterTitle       string
	CommittedAt        int64
	Source             string
	ChangeRequestsJson string
}

func (q *Queries) CreateStoryHarnessBatch(ctx context.Context, arg CreateStoryHarnessBatchParams) error {
	_, err := q.db.ExecContext(ctx, createStoryHarnessBatch,
		arg.BatchID,
		arg.ProjectID,
		arg.ChapterID,
		arg.ChapterTitle,
		arg.CommittedAt,
		arg.Source,
		arg.ChangeRequestsJson,
	)
	return err
}

const createStoryHarnessChangeRequest = `-- name: CreateStoryHarnessChangeRequest :exec
INSERT INTO story_harness_change_requests (
    id,
    batch_id,
    project_id,
    chapter_id,
    category,
    priority,
    status,
    title,
    description,
    suggested_change_json,
    evidence_json,
    source
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateStoryHarnessChangeRequestParams struct {
	ID                  string
	BatchID             string
	ProjectID           string
	ChapterID           string
	Category            string
	Priority            string
	Status              string
	Title               string
	Description         string
	SuggestedChangeJson string
	EvidenceJson        string
	Source              string
}

func (q *Queries) CreateStoryHarnessChangeRequest(ctx context.Context, arg CreateStoryHarnessChangeRequestParams) error {
	_, err := q.db.ExecContext(ctx, createStoryHarnessChangeRequest,
		arg.ID,
		arg.BatchID,
		arg.ProjectID,
		arg.ChapterID,
		arg.Category,
		arg.Priority,
		arg.Status,
		arg.Title,
		arg.Description,
		arg.SuggestedChangeJson,
		arg.EvidenceJson,
		arg.Source,
	)
	return err
}

const deleteStoryHarnessChangeRequestsByChapter = `-- name: DeleteStoryHarnessChangeRequestsByChapter :exec
DELETE FROM story_harness_change_requests
WHERE chapter_id = ?
`

func (q *Queries) DeleteStoryHarnessChangeRequestsByChapter(ctx context.Context, chapterID string) error {
	_, err := q.db.ExecContext(ctx, deleteStoryHarnessChangeRequestsByChapter, chapterID)
	return err
}

const getLatestAcceptedStoryHarnessChangeRequestID = `-- name: GetLatestAcceptedStoryHarnessChangeRequestID :one
SELECT COALESCE(id, '')
FROM story_harness_change_requests
WHERE chapter_id = ? AND status = 'accepted'
ORDER BY updated_at DESC, created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAcceptedStoryHarnessChangeRequestID(ctx context.Context, chapterID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getLatestAcceptedStoryHarnessChangeRequestID, chapterID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getLatestStoryHarnessBatch = `-- name: GetLatestStoryHarnessBatch :one
SELECT
    batch_id,
    project_id,
    chapter_id,
    COALESCE(chapter_title, '') AS chapter_title,
    committed_at,
    source,
    change_requests_json,
    created_at,
    updated_at
FROM story_harness_batches
WHERE project_id = ? AND chapter_id = ?
ORDER BY committed_at DESC
LIMIT 1
`

type GetLatestStoryHarnessBatchParams struct {
	ProjectID string
	ChapterID string
}

func (q *Queries) GetLatestStoryHarnessBatch(ctx context.Context, arg GetLatestStoryHarnessBatchParams) (StoryHarnessBatch, error) {
	row := q.db.QueryRowContext(ctx, getLatestStoryHarnessBatch, arg.ProjectID, arg.ChapterID)
	var i StoryHarnessBatch
	err := row.Scan(
		&i.BatchID,
		&i.ProjectID,
		&i.ChapterID,
		&i.ChapterTitle,
		&i.CommittedAt,
		&i.Source,
		&i.ChangeRequestsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoryHarnessChangeRequestByID = `-- name: GetStoryHarnessChangeRequestByID :one
SELECT
    id,
    batch_id,
    project_id,
    chapter_id,
    category,
    priority,
    status,
    title,
    COALESCE(description, '') AS description,
    suggested_change_json,
    evidence_json,
    source,
    created_at,
    updated_at
FROM story_harness_change_requests
WHERE id = ?
`

func (q *Queries) GetStoryHarnessChangeRequestByID(ctx context.Context, id string) (StoryHarnessChangeRequest, error) {
	row := q.db.QueryRowContext(ctx, getStoryHarnessChangeRequestByID, id)
	var i StoryHarnessChangeRequest
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.ProjectID,
		&i.ChapterID,
		&i.Category,
		&i.Priority,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.SuggestedChangeJson,
		&i.EvidenceJson,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStoryHarnessChangeRequestsByChapterAndStatus = `-- name: ListStoryHarnessChangeRequestsByChapterAndStatus :many
SELECT
    id,
    batch_id,
    project_id,
    chapter_id,
    category,
    priority,
    status,
    title,
    COALESCE(description, '') AS description,
    suggested_change_json,
    evidence_json,
    source,
    created_at,
    updated_at
FROM story_harness_change_requests
WHERE chapter_id = ? AND status = ?
ORDER BY created_at DESC, updated_at DESC
`

type ListStoryHarnessChangeRequestsByChapterAndStatusParams struct {
	ChapterID string
	Status    string
}

func (q *Queries) ListStoryHarnessChangeRequestsByChapterAndStatus(ctx context.Context, arg ListStoryHarnessChangeRequestsByChapterAndStatusParams) ([]StoryHarnessChangeRequest, error) {
	rows, err := q.db.QueryContext(ctx, listStoryHarnessChangeRequestsByChapterAndStatus, arg.ChapterID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoryHarnessChangeRequest
	for rows.Next() {
		var i StoryHarnessChangeRequest
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.ProjectID,
			&i.ChapterID,
			&i.Category,
			&i.Priority,
			&i.Status,
			&i.Title,
			&i.Description,
			&i.SuggestedChangeJson,
			&i.EvidenceJson,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStoryHarnessChangeRequestStatus = `-- name: UpdateStoryHarnessChangeRequestStatus :execrows
UPDATE story_harness_change_requests
SET status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateStoryHarnessChangeRequestStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateStoryHarnessChangeRequestStatus(ctx context.Context, arg UpdateStoryHarnessChangeRequestStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateStoryHarnessChangeRequestStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
