// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: timelines.sql

package sqlc

import (
	"context"
)

const createTimeline = `-- name: CreateTimeline :exec
INSERT INTO timelines (
    id,
    project_id,
    name,
    description,
    start_time_json,
    end_time_json
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTimelineParams struct {
	ID            string
	ProjectID     string
	Name          string
	Description   string
	StartTimeJson string
	EndTimeJson   string
}

func (q *Queries) CreateTimeline(ctx context.Context, arg CreateTimelineParams) error {
	_, err := q.db.ExecContext(ctx, createTimeline,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.StartTimeJson,
		arg.EndTimeJson,
	)
	return err
}

const createTimelineEvent = `-- name: CreateTimelineEvent :exec
INSERT INTO timeline_events (
    id,
    project_id,
    timeline_id,
    title,
    description,
    story_time_json,
    duration,
    impact,
    participants_json,
    location_ids_json,
    chapter_ids_json,
    event_type,
    importance
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTimelineEventParams struct {
	ID               string
	ProjectID        string
	TimelineID       string
	Title            string
	Description      string
	StoryTimeJson    string
	Duration         string
	Impact           string
	ParticipantsJson string
	LocationIdsJson  string
	ChapterIdsJson   string
	EventType        string
	Importance       int64
}

func (q *Queries) CreateTimelineEvent(ctx context.Context, arg CreateTimelineEventParams) error {
	_, err := q.db.ExecContext(ctx, createTimelineEvent,
		arg.ID,
		arg.ProjectID,
		arg.TimelineID,
		arg.Title,
		arg.Description,
		arg.StoryTimeJson,
		arg.Duration,
		arg.Impact,
		arg.ParticipantsJson,
		arg.LocationIdsJson,
		arg.ChapterIdsJson,
		arg.EventType,
		arg.Importance,
	)
	return err
}

const deleteTimelineByID = `-- name: DeleteTimelineByID :execrows
DELETE FROM timelines
WHERE id = ?
`

func (q *Queries) DeleteTimelineByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTimelineByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTimelineEventByID = `-- name: DeleteTimelineEventByID :execrows
DELETE FROM timeline_events
WHERE id = ?
`

func (q *Queries) DeleteTimelineEventByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTimelineEventByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTimelineByID = `-- name: GetTimelineByID :one
SELECT
    id,
    project_id,
    name,
    COALESCE(description, '') AS description,
    start_time_json,
    end_time_json,
    created_at,
    updated_at
FROM timelines
WHERE id = ?
`

func (q *Queries) GetTimelineByID(ctx context.Context, id string) (Timeline, error) {
	row := q.db.QueryRowContext(ctx, getTimelineByID, id)
	var i Timeline
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.StartTimeJson,
		&i.EndTimeJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTimelineEventByID = `-- name: GetTimelineEventByID :one
SELECT
    id,
    project_id,
    timeline_id,
    title,
    COALESCE(description, '') AS description,
    story_time_json,
    COALESCE(duration, '') AS duration,
    COALESCE(impact, '') AS impact,
    participants_json,
    location_ids_json,
    chapter_ids_json,
    COALESCE(event_type, 'plot') AS event_type,
    COALESCE(importance, 5) AS importance,
    created_at,
    updated_at
FROM timeline_events
WHERE id = ?
`

func (q *Queries) GetTimelineEventByID(ctx context.Context, id string) (TimelineEvent, error) {
	row := q.db.QueryRowContext(ctx, getTimelineEventByID, id)
	var i TimelineEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TimelineID,
		&i.Title,
		&i.Description,
		&i.StoryTimeJson,
		&i.Duration,
		&i.Impact,
		&i.ParticipantsJson,
		&i.LocationIdsJson,
		&i.ChapterIdsJson,
		&i.EventType,
		&i.Importance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTimelineEventsByTimeline = `-- name: ListTimelineEventsByTimeline :many
SELECT
    id,
    project_id,
    timeline_id,
    title,
    COALESCE(description, '') AS description,
    story_time_json,
    COALESCE(duration, '') AS duration,
    COALESCE(impact, '') AS impact,
    participants_json,
    location_ids_json,
    chapter_ids_json,
    COALESCE(event_type, 'plot') AS event_type,
    COALESCE(importance, 5) AS importance,
    created_at,
    updated_at
FROM timeline_events
WHERE timeline_id = ?
ORDER BY created_at ASC, updated_at ASC
`

func (q *Queries) ListTimelineEventsByTimeline(ctx context.Context, timelineID string) ([]TimelineEvent, error) {
	rows, err := q.db.QueryContext(ctx, listTimelineEventsByTimeline, timelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimelineEvent
	for rows.Next() {
		var i TimelineEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TimelineID,
			&i.Title,
			&i.Description,
			&i.StoryTimeJson,
			&i.Duration,
			&i.Impact,
			&i.ParticipantsJson,
			&i.LocationIdsJson,
			&i.ChapterIdsJson,
			&i.EventType,
			&i.Importance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelinesByProject = `-- name: ListTimelinesByProject :many
SELECT
    id,
    project_id,
    name,
    COALESCE(description, '') AS description,
    start_time_json,
    end_time_json,
    created_at,
    updated_at
FROM timelines
WHERE project_id = ?
ORDER BY created_at ASC, updated_at ASC
`

func (q *Queries) ListTimelinesByProject(ctx context.Context, projectID string) ([]Timeline, error) {
	rows, err := q.db.QueryContext(ctx, listTimelinesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Timeline
	for rows.Next() {
		var i Timeline
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.StartTimeJson,
			&i.EndTimeJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimelineByID = `-- name: UpdateTimelineByID :execrows
UPDATE timelines
SET name = ?,
    description = ?,
    start_time_json = ?,
    end_time_json = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTimelineByIDParams struct {
	Name          string
	Description   string
	StartTimeJson string
	EndTimeJson   string
	ID            string
}

func (q *Queries) UpdateTimelineByID(ctx context.Context, arg UpdateTimelineByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTimelineByID,
		arg.Name,
		arg.Description,
		arg.StartTimeJson,
		arg.EndTimeJson,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTimelineEventByID = `-- name: UpdateTimelineEventByID :execrows
UPDATE timeline_events
SET title = ?,
    description = ?,
    story_time_json = ?,
    duration = ?,
    impact = ?,
    participants_json = ?,
    location_ids_json = ?,
    chapter_ids_json = ?,
    event_type = ?,
    importance = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTimelineEventByIDParams struct {
	Title            string
	Description      string
	StoryTimeJson    string
	Duration         string
	Impact           string
	ParticipantsJson string
	LocationIdsJson  string
	ChapterIdsJson   string
	EventType        string
	Importance       int64
	ID               string
}

func (q *Queries) UpdateTimelineEventByID(ctx context.Context, arg UpdateTimelineEventByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTimelineEventByID,
		arg.Title,
		arg.Description,
		arg.StoryTimeJson,
		arg.Duration,
		arg.Impact,
		arg.ParticipantsJson,
		arg.LocationIdsJson,
		arg.ChapterIdsJson,
		arg.EventType,
		arg.Importance,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
