// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: volumes.sql

package sqlc

import (
	"context"
)

const createVolume = `-- name: CreateVolume :exec
INSERT INTO volumes (id, project_id, title, sort_order)
VALUES (?, ?, ?, ?)
`

type CreateVolumeParams struct {
	ID        string
	ProjectID string
	Title     string
	SortOrder int64
}

func (q *Queries) CreateVolume(ctx context.Context, arg CreateVolumeParams) error {
	_, err := q.db.ExecContext(ctx, createVolume,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.SortOrder,
	)
	return err
}

const deleteVolumeByID = `-- name: DeleteVolumeByID :execrows
DELETE FROM volumes
WHERE id = ?
`

func (q *Queries) DeleteVolumeByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVolumeByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getVolumeByID = `-- name: GetVolumeByID :one
SELECT
    id,
    project_id,
    title,
    sort_order,
    created_at
FROM volumes
WHERE id = ?
`

func (q *Queries) GetVolumeByID(ctx context.Context, id string) (Volume, error) {
	row := q.db.QueryRowContext(ctx, getVolumeByID, id)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listVolumesByProject = `-- name: ListVolumesByProject :many
SELECT
    id,
    project_id,
    title,
    sort_order,
    created_at
FROM volumes
WHERE project_id = ?
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListVolumesByProject(ctx context.Context, projectID string) ([]Volume, error) {
	rows, err := q.db.QueryContext(ctx, listVolumesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Volume
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextVolumeSortOrder = `-- name: NextVolumeSortOrder :one
SELECT COALESCE(MAX(sort_order), -1) + 1
FROM volumes
WHERE project_id = ?
`

func (q *Queries) NextVolumeSortOrder(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextVolumeSortOrder, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const reorderVolumeByID = `-- name: ReorderVolumeByID :exec
UPDATE volumes
SET sort_order = ?
WHERE id = ? AND project_id = ?
`

type ReorderVolumeByIDParams struct {
	SortOrder int64
	ID        string
	ProjectID string
}

func (q *Queries) ReorderVolumeByID(ctx context.Context, arg ReorderVolumeByIDParams) error {
	_, err := q.db.ExecContext(ctx, reorderVolumeByID, arg.SortOrder, arg.ID, arg.ProjectID)
	return err
}

const updateVolumeByID = `-- name: UpdateVolumeByID :execrows
UPDATE volumes
SET title = ?,
    sort_order = ?
WHERE id = ?
`

type UpdateVolumeByIDParams struct {
	Title     string
	SortOrder int64
	ID        string
}

func (q *Queries) UpdateVolumeByID(ctx context.Context, arg UpdateVolumeByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVolumeByID, arg.Title, arg.SortOrder, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
