// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ai} from '../models';

export function AICall(arg1:ai.Config,arg2:string,arg3:string):Promise<string>;

export function InitDatabase():Promise<void>;
